import = ["/home/justin/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.bold]
family = "FantasqueSansMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansMono Nerd Font"
style = "Italic"

[font.normal]
family = "FantasqueSansMono Nerd Font"
style = "Regular"

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 0.8

[window.padding]
x = 5
y = 5
