import = ["/home/pacfrog/.config/alacritty/catppuccin/catppuccin-frappe.toml"]
#import = ["/home/pacfrog/.config/alacritty/dracula/dracula.toml"]

[shell]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "Full"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.85

[mouse]
hide_when_typing = true
